[package]
name = "ratelimiter"
version = "0.1.2"
authors = ["John Edmonds <john.a.edmonds@gmail.com>"]
description = "Rate limiter for Rust."
repository = "https://github.com/johnedmonds/ratelimiter"
license = "MIT"

[dependencies]
futures = "0.2.0"